name: Build and Test
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 21 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy
      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
          vcs-repo-file-url: "${{ github.workspace }}/tools/dependency.repos"
